openapi: 3.0.1
info:
  title: Users API
  description: 'Bootcamp DIO: CRUD /users api'
  version: '1'
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /users/{username}:
    get:
      tags:
        - users
      summary: Busca usuario
      operationId: getUserByUsername
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: usuario encontrado!
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: usuario nao encontrado
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
    put:
      tags:
        - users
      summary: Atualiza usuario
      operationId: updateUser
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: usuario atualizado!
          content:
            '*/*':
              schema:
                type: object
        '400':
          description: username nulo ou vazio
          content:
            '*/*':
              schema:
                type: object
        '404':
          description: usuario nao encontrado
          content:
            '*/*':
              schema:
                type: object
    delete:
      tags:
        - users
      summary: Atualiza usuario
      operationId: deleteUser
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: usuario apagado!
          content:
            '*/*':
              schema:
                type: object
        '404':
          description: usuario nao encontrado
          content:
            '*/*':
              schema:
                type: object
  /users:
    post:
      tags:
        - users
      summary: Cadastro de um novo usuario
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '201':
          description: usuario criado!
          content:
            '*/*':
              schema:
                type: object
        '400':
          description: username nulo ou vazio
          content:
            '*/*':
              schema:
                type: object
        '409':
          description: usuario existente
          content:
            '*/*':
              schema:
                type: object
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        email:
          type: string
        age:
          type: integer
          format: int32
